POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "first_name": "aniebiet",
    "last_name": "afia",
    "email": "aniebietafia@gmail.com",
    "password": "Test1234$",
    "confirm_password": "Test1234$",
    "phone_number": "08012345678",
    "gender": "male",
    "country_code": "+234"
}

POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "aniebietafia@gmail.com",
    "password": "Test1234$"
}