POST http://localhost:3001/api/auth/register
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="image03.jpg"
Content-Type: image/jpg

< ./assets/image03.jpg
--WebKitFormBoundary
Content-Disposition: form-data; name="first_name"

michelle
--WebKitFormBoundary
Content-Disposition: form-data; name="last_name"

bloomfield
--WebKitFormBoundary
Content-Disposition: form-data; name="email"

goldenlee87@gmail.com
--WebKitFormBoundary
Content-Disposition: form-data; name="password"

Test1234$
--WebKitFormBoundary
Content-Disposition: form-data; name="confirm_password"

Test1234$
--WebKitFormBoundary
Content-Disposition: form-data; name="phone_number"

08098194719
--WebKitFormBoundary
Content-Disposition: form-data; name="gender"

female
--WebKitFormBoundary
Content-Disposition: form-data; name="country_code"

234
--WebKitFormBoundary
Content-Disposition: form-data; name="privacy_policy"

true
--WebKitFormBoundary
Content-Disposition: form-data; name="terms_and_conditions"

true
--WebKitFormBoundary
Content-Disposition: form-data; name="marketing"

true
--WebKitFormBoundary--