POST http://localhost:3001/api/auth/register
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="image04.jpg"
Content-Type: image/jpg

< ./assets/image01.jpg
--WebKitFormBoundary
Content-Disposition: form-data; name="first_name"

aniebiet
--WebKitFormBoundary
Content-Disposition: form-data; name="last_name"

afia
--WebKitFormBoundary
Content-Disposition: form-data; name="email"

aniebietafia@gmail.com
--WebKitFormBoundary
Content-Disposition: form-data; name="password"

Test1234$
--WebKitFormBoundary
Content-Disposition: form-data; name="confirm_password"

Test1234$
--WebKitFormBoundary
Content-Disposition: form-data; name="phone_number"

08098194719
--WebKitFormBoundary
Content-Disposition: form-data; name="gender"

male
--WebKitFormBoundary
Content-Disposition: form-data; name="country_code"

234
--WebKitFormBoundary
Content-Disposition: form-data; name="privacy_policy"

true
--WebKitFormBoundary
Content-Disposition: form-data; name="terms_and_conditions"

true
--WebKitFormBoundary
Content-Disposition: form-data; name="marketing"

false
--WebKitFormBoundary--


POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "first_name": "david",
    "last_name": "lacroix",
    "email": "aniebietafia@gmail.com",
    "password": "Test1234$",
    "confirm_password": "Test1234$",
    "gender": "male",
    "phone_number": "08098194719",
    "country_code": "234",
    "privacy_policy": "true",
    "terms_and_conditions": "true",
    "marketing_consent": "false"
}