POST http://localhost:3001/api/auth/register
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="image04.jpg"
Content-Type: image/jpg

< ./assets/image04.jpg
--WebKitFormBoundary
Content-Disposition: form-data; name="first_name"

barbara
--WebKitFormBoundary
Content-Disposition: form-data; name="last_name"

clayton
--WebKitFormBoundary
Content-Disposition: form-data; name="email"

aniebiet.career.dev@gmail.com
--WebKitFormBoundary
Content-Disposition: form-data; name="password"

Test1234$
--WebKitFormBoundary
Content-Disposition: form-data; name="confirm_password"

Test1234$
--WebKitFormBoundary
Content-Disposition: form-data; name="phone_number"

08075955288
--WebKitFormBoundary
Content-Disposition: form-data; name="gender"

female
--WebKitFormBoundary
Content-Disposition: form-data; name="country_code"

234
--WebKitFormBoundary
Content-Disposition: form-data; name="privacy_policy"

true
--WebKitFormBoundary
Content-Disposition: form-data; name="terms_and_conditions"

true
--WebKitFormBoundary
Content-Disposition: form-data; name="marketing"

true
--WebKitFormBoundary--