PUT http://localhost:3001/api/user/909e3380-df25-4985-aa19-d01b4debb152
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MDllMzM4MC1kZjI1LTQ5ODUtYWExOS1kMDFiNGRlYmIxNTIiLCJmaXJzdF9uYW1lIjoiU2FuZHJhIiwibGFzdF9uYW1lIjoiVHJhdmlzIiwiZW1haWwiOiJhZmlhYW5pZWJpZXQwQGdtYWlsLmNvbSIsInBob25lX251bWJlciI6IisyMzQ4MDI3ODcyNDE1Iiwicm9sZSI6InVzZXIiLCJ2ZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzI4OTA2MjAzLCJleHAiOjE3Mjg5MDk4MDMsImF1ZCI6ImxvY2FsaG9zdDozMDAxIiwiaXNzIjoibG9jYWxob3N0OjMwMDEifQ.u75Oxho48bKgpD09BcPPdtuvexv5iHZ3dqyWyNf_ZFw

{
    "isVerified": false
}


PUT http://localhost:3001/api/user/909e3380-df25-4985-aa19-d01b4debb152
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MDllMzM4MC1kZjI1LTQ5ODUtYWExOS1kMDFiNGRlYmIxNTIiLCJmaXJzdF9uYW1lIjoiU2FuZHJhIiwibGFzdF9uYW1lIjoiVHJhdmlzIiwiZW1haWwiOiJhZmlhYW5pZWJpZXQwQGdtYWlsLmNvbSIsInBob25lX251bWJlciI6IisyMzQ4MDI3ODcyNDE1Iiwicm9sZSI6InVzZXIiLCJ2ZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzI4OTA2MjAzLCJleHAiOjE3Mjg5MDk4MDMsImF1ZCI6ImxvY2FsaG9zdDozMDAxIiwiaXNzIjoibG9jYWxob3N0OjMwMDEifQ.u75Oxho48bKgpD09BcPPdtuvexv5iHZ3dqyWyNf_ZFw

{
    "first_name": "Lisa",
    "marketing_consent": false
}