GET http://localhost:3001/api/user/70284b5a-c275-4b4c-bfb4-8e3a95665eba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MDI4NGI1YS1jMjc1LTRiNGMtYmZiNC04ZTNhOTU2NjVlYmEiLCJmaXJzdF9uYW1lIjoiQW5pZWJpZXQiLCJsYXN0X25hbWUiOiJBZmlhIiwiZW1haWwiOiJhbmllYmlldGFmaWFAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiKzIzNDgwNDI3NDU2NDciLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJ2ZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzI2NzkwMzQwLCJleHAiOjE3MjY3OTM5NDAsImF1ZCI6ImxvY2FsaG9zdDozMDAxIiwiaXNzIjoibG9jYWxob3N0OjMwMDEifQ.Lb-QLpC8xXjxqN00QKTLmYkZnqAfjc0RLR5QtB2XSZw


GET http://localhost:3001/api/user/c5ed03dc-84fc-4739-a9a3-d14320c586a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWVkMDNkYy04NGZjLTQ3MzktYTlhMy1kMTQzMjBjNTg2YTEiLCJmaXJzdF9uYW1lIjoiU2FyYWgiLCJsYXN0X25hbWUiOiJNaWNoYWVsIiwiZW1haWwiOiJhbmllYmlldGFmaWE4N0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIrMjM0ODAyNzg3MjQxNSIsInJvbGUiOiJ1c2VyIiwidmVyaWZpZWQiOnRydWUsImlhdCI6MTcyNjc5MDQwOCwiZXhwIjoxNzI2Nzk0MDA4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.KG2NSr_Yhp5Fs96jHGS9wi96KfSBH1M149hBgva6DJI