POST http://localhost:3001/api/user/reset-password/afiaaniebiet0@gmail.com/58f7a1e1f17c2e724e67de45dbe304d2be91026904ab5dc88493ff5c9c6cf747d05b232257e9dcd0
Content-Type: application/json

{
    "new_password": "Test1234$",
    "confirm_password": "Test1234$"
}