GET http://localhost:3001/api/users/c5ed03dc-84fc-4739-a9a3-d14320c586a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWVkMDNkYy04NGZjLTQ3MzktYTlhMy1kMTQzMjBjNTg2YTEiLCJmaXJzdF9uYW1lIjoiU2FyYWgiLCJsYXN0X25hbWUiOiJNaWNoYWVsIiwiZW1haWwiOiJhbmllYmlldGFmaWE4N0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIrMjM0ODAyNzg3MjQxNSIsInJvbGUiOiJ1c2VyIiwidmVyaWZpZWQiOnRydWUsImlhdCI6MTcyNjY2Njk2NywiZXhwIjoxNzI2NjcwNTY3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.EmHOWaVpq2JLWxyBK7hBaYvZQ73Fj3kyIQOiXVdPXlc