GET http://localhost:3001/api/users/c5ed03dc-84fc-4739-a9a3-d14320c586a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MDI4NGI1YS1jMjc1LTRiNGMtYmZiNC04ZTNhOTU2NjVlYmEiLCJmaXJzdF9uYW1lIjoiQW5pZWJpZXQiLCJsYXN0X25hbWUiOiJBZmlhIiwiZW1haWwiOiJhbmllYmlldGFmaWFAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiKzIzNDgwNDI3NDU2NDciLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJ2ZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzI2Njk2ODU1LCJleHAiOjE3MjY3MDA0NTUsImF1ZCI6ImxvY2FsaG9zdDozMDAxIiwiaXNzIjoibG9jYWxob3N0OjMwMDEifQ.Nvceohv_3GKLb8RXDzBMY3j4uR1Sd9Asc7W97QcCFM4

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjNWVkMDNkYy04NGZjLTQ3MzktYTlhMy1kMTQzMjBjNTg2YTEiLCJmaXJzdF9uYW1lIjoiU2FyYWgiLCJsYXN0X25hbWUiOiJNaWNoYWVsIiwiZW1haWwiOiJhbmllYmlldGFmaWE4N0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIrMjM0ODAyNzg3MjQxNSIsInJvbGUiOiJ1c2VyIiwidmVyaWZpZWQiOnRydWUsImlhdCI6MTcyNjY5NTUyMSwiZXhwIjoxNzI2Njk5MTIxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.2nl1w97TuNPdFJhwyhXxfYv92gTXlzqJBM_tUZ4g3cI