POST http://localhost:3001/api/user/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Mjk5NjIzYS1lMDAwLTQ2NjAtYWZhZi0xOTkzNDMzZGNlNGMiLCJmaXJzdF9uYW1lIjoiQW5pZWJpZXQiLCJsYXN0X25hbWUiOiJXaHl0ZSIsImVtYWlsIjoiYW5pZWJpZXRhZmlhODdAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiKzIzNDgwNjc1ODE5MjciLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJ2ZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzI3MDk0MjgxLCJleHAiOjE3MjcwOTc4ODEsImF1ZCI6ImxvY2FsaG9zdDozMDAxIiwiaXNzIjoibG9jYWxob3N0OjMwMDEifQ.EHg4mmGRTsDPeZbrcRQSVIOGUEsd2GeW6TU3wsq93fg
Content-Type: application/json

{
    "old_password": "Test1234!",
    "new_password": "Test1234$",
    "confirm_password": "Test1234$"
}

//const { token } = require('../../../../auth/http/auth.login.endpoint.http');