GET http://localhost:3001/users/1

GET http://localhost:3001/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjI2N2IxMS02NmYzLTQ3MjAtYjM1MS01ZjlkNDc0OGQ3M2YiLCJmaXJzdF9uYW1lIjoiQW5pZWJpZXQiLCJsYXN0X25hbWUiOiJBZmlhIiwiZW1haWwiOiJhbmllYmlldGFmaWFAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiKzIzNDgwMTIzNDU2NzgiLCJyb2xlIjoidXNlciIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3MjU1NDA4NzQsImV4cCI6MTcyNTU0NDQ3NCwiYXVkIjoibG9jYWxob3N0OjMwMDEiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMSJ9.G04DtZ6ZEKc0GM5tLVPXKK6H-GHiw12gDRUeqViexME

GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZjI2N2IxMS02NmYzLTQ3MjAtYjM1MS01ZjlkNDc0OGQ3M2YiLCJmaXJzdF9uYW1lIjoiQW5pZWJpZXQiLCJsYXN0X25hbWUiOiJBZmlhIiwiZW1haWwiOiJhbmllYmlldGFmaWFAZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiKzIzNDgwMTIzNDU2NzgiLCJyb2xlIjoidXNlciIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3MjU1NDA4NzQsImV4cCI6MTcyNTU0NDQ3NCwiYXVkIjoibG9jYWxob3N0OjMwMDEiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMSJ9.G04DtZ6ZEKc0GM5tLVPXKK6H-GHiw12gDRUeqViexME

GET http://localhost:3001/api/users/verify-email
?email=aniebietafia@gmail.com
&email_verification_token=3ff5560e246e5bcc4336965c580b45ec1ed771ad4e395ca5abd825f99e0493a347dcd4acd7efc661


POST http://localhost:3001/api/users/verify-phone
Content-Type: application/json

{
    "otp": 631386,
    "phone_number": "+23480278724166"
}