name: CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./brints-estate-api/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: ./brints-estate-api
        run: yarn install

      - name: Prettier Format
        working-directory: ./brints-estate-api
        run: yarn format

      - name: Run tests
        working-directory: ./brints-estate-api
        run: yarn test --passWithNoTests

      - name: Build
        working-directory: ./brints-estate-api
        run: yarn build
